# Russian translations for Django package.
# Copyright (C) Django Software Foundation and contributors
# This file is distributed under the same license as the Django package.
# Automatically generated, 2013.
#
msgid ""
msgstr ""
"Project-Id-Version: Django 1.5\n"
"Report-Msgid-Bugs-To: \n"
"POT-Creation-Date: 2020-02-13 22:13+0300\n"
"PO-Revision-Date: 2013-04-10 17:15\n"
"Last-Translator: Viktor Tyshchenko <tyvik8@gmail.com>\n"
"Language-Team: none\n"
"Language: ru\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Plural-Forms: nplurals=3; plural=(n%10==1 && n%100!=11 ? 0 : n%10>=2 && n"
"%10<=4 && (n%100<10 || n%100>=20) ? 1 : 2);\n"

# b068ed96325d484b80be8f977bd29b75
#: ../../releases/1.4.6.txt:3
msgid "Django 1.4.6 release notes"
msgstr "Релиз Django 1.4.6"

# 5197286d19be4275a744e9c46684be36
#: ../../releases/1.4.6.txt:5
msgid "*August 13, 2013*"
msgstr "*13 августа 2013*"

# 30a96ff352ae4dadb5c0caf6475a32b9
#: ../../releases/1.4.6.txt:7
msgid ""
"Django 1.4.6 fixes one security issue present in previous Django releases in "
"the 1.4 series, as well as one other bug."
msgstr ""
"Django 1.4.6 исправляет ошибку безопасности в предыдущих релизах, а также "
"закрывает ещё один баг."

# 33479660b157429b97df454130abc3ff
#: ../../releases/1.4.6.txt:10
msgid "This is the sixth bugfix/security release in the Django 1.4 series."
msgstr "Это шестой патч в ветке Django 1.4."

# 5799bf3486e3403587105956f3d6b32b
#: ../../releases/1.4.6.txt:13
msgid "Mitigated possible XSS attack via user-supplied redirect URLs"
msgstr "Смягчение возможной XSS-атаки через пользовательское перенаправление"

# 82510db06a3f4d73ac5e0406119e2ee3
#: ../../releases/1.4.6.txt:15
#, fuzzy
msgid ""
"Django relies on user input in some cases (e.g. ``django.contrib.auth.views."
"login()``, ``django.contrib.comments``, and :doc:`i18n </topics/i18n/"
"index>`) to redirect the user to an \"on success\" URL. The security checks "
"for these redirects (namely ``django.utils.http.is_safe_url()``) didn't "
"check if the scheme is ``http(s)`` and as such allowed ``javascript:...`` "
"URLs to be entered. If a developer relied on ``is_safe_url()`` to provide "
"safe redirect targets and put such a URL into a link, they could suffer from "
"a XSS attack. This bug doesn't affect Django currently, since we only put "
"this URL into the ``Location`` response header and browsers seem to ignore "
"JavaScript there."
msgstr ""
"В некоторых случаях Django полагается на действие пользователя (например, в :"
"func:`django.contrib.auth.views.login`, :mod:`django.contrib.comments`, и :"
"doc:`i18n </topics/i18n/index>`) при перенаправлении пользователя на "
"\"успешную\" страницу. Проверка безопасности в таком случае (``django.util."
"http.is_safe_url()``) не сработает, если протокол ``http(s)`` и разрешены "
"``javascript:...`` URL`ы для ввода. Если разработчик полагался на "
"``is_safe_url()`` при обеспечении безопасности редиректа и добавил такой URL "
"в ссылку, то злоумышленник может провести XSS-атаку. В настоящий момент мы "
"добавляем этот URL в заголовок ``Location`` ответа, так что браузеры будут "
"игнорировать опасный JavaScript."

# c690d698e0854befa8062e8146b2ad09
#: ../../releases/1.4.6.txt:27
msgid "Bugfixes"
msgstr "Исправления"

# 924360d97aaf4fc693e2b793f880faa9
#: ../../releases/1.4.6.txt:29
#, fuzzy
msgid ""
"Fixed an obscure bug with the :func:`~django.test.override_settings` "
"decorator. If you hit an ``AttributeError: 'Settings' object has no "
"attribute '_original_allowed_hosts'`` exception, it's probably fixed "
"(#20636)."
msgstr ""
"Исправлена непонятная ошибка в декораторе :func:`~django.test.utils."
"override_settings`. Если вы получали исключение ``AttributeError: 'Settings' "
"object has no attribute '_original_allowed_hosts'``, то это ваш случай "
"(#20636)."
